FROM ubuntu:xenial
ENV http_proxy http://proxy-us.intel.com:911
ENV https_proxy https://proxy-us.intel.com:911
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    iproute2 \
    iptables \
 && rm -rf /var/lib/apt/lists/*

ADD istio-iptables.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/istio-iptables.sh"]
