FROM ubuntu:xenial

RUN apt-get update

RUN apt-get install -y softhsm
RUN apt-get install -y softhsm2
RUN apt-get install -y libsofthsm2
RUN apt-get install -y opensc
RUN apt-get install -y libltdl-dev

RUN mkdir /var/lib/softhsm/tokens
COPY import.sh /
RUN chmod +x /import.sh

ADD istio_ca /usr/local/bin/istio_ca

COPY istio_ca.crt /usr/local/bin/istio_ca.crt
COPY istio_ca.key /usr/local/bin/istio_ca.key


ENTRYPOINT [ "/usr/local/bin/istio_ca", \
"--protected-ca-key", \
"--protected-ca-key-label", "catestkey", \
"--protected-ca-key-id", "13107", \
"--protected-token-pin", "999999999", \
"--signing-cert", "/usr/local/bin/istio_ca.crt", \
"--signing-key", "/usr/local/bin/istio_ca.key", \
"--root-cert", "/usr/local/bin/istio_ca.crt", \
"--grpc-port", "8060" ]
