FROM ubuntu:xenial

RUN apt-get update

RUN apt-get install -y softhsm
RUN apt-get install -y softhsm2
RUN apt-get install -y libsofthsm2
RUN apt-get install -y opensc
RUN apt-get install -y libltdl-dev
RUN apt-get install -y openssl

RUN mkdir /var/lib/softhsm/tokens
COPY import.sh /
RUN chmod +x /import.sh

ADD istio_ca /usr/local/bin/istio_ca

COPY istio_ca.crt /usr/local/bin/istio_ca.crt
COPY istio_ca.key /usr/local/bin/istio_ca.key

COPY ca-chain.cert.pem /usr/local/bin/ca-chain.cert.pem
COPY ca-root.cert.pem /usr/local/bin/ca-root.cert.pem
COPY intermediate.cert.pem /usr/local/bin/intermediate.cert.pem
COPY intermediate.key.pem /usr/local/bin/intermediate.key.pem


ENTRYPOINT [ "/usr/local/bin/istio_ca" ]
